my_string = input('Введите строку: ')
print('Длина строки (символов): ' , len(my_string))
print('Верхний регистр: ' ,my_string .upper())
print('Нижний регистр: ' ,my_string .lower())
print('Без пробелов: ' ,my_string .replace(' ', ''))
print('Первый символ строки: ', my_string[0])
print('Последний символ строки: ', my_string[-1])